### ISSUE TITLE
Publish our experience with the RQM/EE430 course

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/rcourse#13]
_From @joelostblom on July 15, 2017 16:25_

Either in https://github.com/openjournals/jose, as a self-published on the UofTCoders website, or elsewhere.

_Copied from original issue: UofTCoders/council#173_

**Comment by joelostblom** [comment]
Things to consider including https://www.californiacivicdata.org/2017/07/12/first-python-notebook-at-sdsu/

**Comment by joelostblom** [comment]
One publication avenue would be on a journals home page as a blog entry, or some overview article, e.g. this one from e-life https://elifesciences.org/labs/cad57bcf/composing-reproducible-manuscripts-using-r-markdown?utm_source=surveymonkey&utm_campaign=reprodocrevs

More journals that could be interested (with examples of similar articles):
- [Biomed Central - Source Code For Biology and Medicine](https://scfbm.biomedcentral.com/articles/10.1186/1751-0473-8-7)
 - [Plos ONE](http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001745)

**Comment by joelostblom** [comment]
We could also just publish in Nature right away https://www.nature.com/articles/s41559-017-0160

**Comment by joelostblom** [comment]
Data carpentry published here http://ijdc.net/index.php/ijdc/article/view/10.1.135

**Comment by lwjohnst86** [comment]
I love this idea and totally think we should do it. I'm going to do a few clean ups, then create a tag of the final course content. If anyone has any strong desires to add or clean something up, let me know.

**Comment by lwjohnst86** [comment]
We now have a DOI to use :smile: https://zenodo.org/record/1117433 and a DOI README badge!

So we can use this DOI when citing the content if/when we write something up about this experience.

**Comment by lwjohnst86** [comment]
It's on my todo list to start a repo for writing a paper on our experience and adding brainstorming, starting a discussion on dividing up the tasks, etc. I hope to get to that end of this week.

**Comment by lwjohnst86** [comment]
We'll also need to consider publication costs... that will likely drive our choice of journal... Unless someone has an idea about how to bypass that.

**Comment by joelostblom** [comment]
Thanks @lwjohnst86!

Fees and links to the publishing section for the journals mentioned earlier in this conversation:

<dl>
  <dt><a href=http://www.ijdc.net/about/submissions> International Journal of digital curation</a></dt>
  <dd>Free. Data Carpentry published here</dd>
  <dt><a href=https://scfbm.biomedcentral.com/submission-guidelines/fees-and-funding> Biomed Central</a></dt>
  <dd>USD 2145. Waives fees on a per author basis. Although UofT is already a member institution and receives 15% off, so I am not sure if they still consider waiving fees.</dd>
  <dt><a href=https://submit.elifesciences.org/html/elife_author_instructions.html#> Elife</a></dt>
  <dd>USD 2500. Waives fees on a per author basis.</dd>
  <dt><a href=https://www.plos.org/fee-assistance> Plos One</a></dt>
  <dd>USD 1500. UofT is not a member, Waives fees on a per author basis.</dd>
  <dt><a href=https://github.com/openjournals/jose> Jose</a></dt>
  <dd>Not accepting submissions yet. No commits in their repo since August.</dd>

</dl>

I could not find anything about UofT having funds available that students could apply for to cover publishing costs, but I can reach out to copyright@library.utoronto.ca and inquire. UofT does host some journals of their own, the only somewhat relevant was [iJournal](http://www.theijournal.ca/index.php/ijournal).

**Comment by lwjohnst86** [comment]
See https://github.com/UofTCoders/paper-rcourse
