### ISSUE TITLE
Define criteria for how the final project will be graded

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/rcourse#14]
_From @joelostblom on July 13, 2017 23:39_

- As per Devin's comments, student's might be keen to know this already from the start and since it is a significant part of their grade, this should be clear upfront.

_Copied from original issue: UofTCoders/council#170_

**Comment by joelostblom** [comment]
@mbonsma will make an inital draft of the rubric. On the meeting we roughly divided it into

1. Working as a team along the way
    a. Continuous contribution to the project. Not just making a chunk of it the last day. Vivid discussion in issues and on pull request.
    b. Contribution from all team members. The team needs to encourage everyone to take part. Self assessment on what they have contributed to the project, which we can double check with their GitHub history.

2. Quality of the final scientific product
    a. Style, both coding and paper/poster. Use of the principles and guidelines that we have taught them during class. 
    b. Motivation behind the hypothesis and the choice of data analyses given their data set. Quality of the analytical work.

Since there are 32 marks available for the final project, we could distribute 8 each per bullet. The scale could be rough, 0 ,4 ,8, or maybe better 0, 2, 4, 6, 8 (I guess maybe we don't need to define 0 mars...) according to the criteria in the rubric. 2b could potentially be worth more points (maybe two more and 1a two less?), although it makes things less streamlined. .

**Comment by mbonsma** [comment]
Draft of rubric:

|     | F | C | A
| -------- | ----------- | ------------------ | ----------------- |
| Contribution to group work and self-assessment |  Student contributed little to project; self-assessed contributions are low in quality and/or quantity | Student contributed adequately to project; made some significant contributions | Student went above and beyond to make project a success; self-assessed contributions are crucial to project | 
| Weekly progress (measured in GitHub commits) |  Several weeks in which no contributions are made to project | Adequate progress on project is made in most weeks | Significant progress is made every week | 
| Content | Missing crucial information; methods and results are inconsistent, not logical, or not adequately explained; conclusions are confusing or unsupported by results; unnecessary information included as clutter | Most essential information included; methods and results are adequately described; conclusions supported by results; most included material is relevant to report | All essential information included; methods and results are succinct, clear, logical, and scientifically valid; conclusions are creative and meaningful; project is concise throughout |
| Style |  Code and writing are poorly organized, poorly formatted, missing units, difficult to read, poorly documented | Code and writing are well-organized, well-formatted, consistent use of units and significant figures | Code and writing are precise and clear throughout, free of errors, well-organized, well-documented, publication-ready |

**Comment by lwjohnst86** [comment]
Thanks @mbonsma! Some comments.

`Significant progress`: should it be maybe `Consistent and substantial progress`? Mainly because what does significant mean, and how do we define it. Thoughts?

`self-assessed contributions`: Maybe also include how self-assessments are consistent between team members and actual contribution (e.g. multiple team members say they contributed substantially, or it doesn't reflect in their commits).

`went above and beyond`: Maybe something like `substantially contributed to project to ensure success`? Since `above and beyond` could possibly be viewed as putting way more effort than is expected for the course. Not sure I'm being clear, but what I mean is I don't want to pressure students with the expectation that they should be working more than they should be... Not sure that makes sense... thoughts?

**Comment by linamnt** [comment]
Looks good! 
re: `went above and beyond` I think it depends if we view getting an A as being "meeting all expectations" or if an A is only for "exceeding expectations"?

**Comment by joelostblom** [comment]
This is great, thanks @mbonsma! 
I think it is good to define three levels as you have done, where F = 0 p, C = 4 p and A = 8 p. If we consider a piece of work to lie between C and A, we can still use the entire point scale and assign a student 6 p for example.

Regarding @lwjohnst86 's comments:

- I think adding "consistent" is redundant, since we write that "Significant progress is made **every week**". I am agnostic to the choice of "substantial" or "significant", in my opinion both are equally unquantified, and either is fine for the rubric since it would be difficult to indicate what amount of progress is sufficient.

- It is a good idea to include a note on consistency between self-assessment and documented GitHub activity.

- I also reacted when I read "above and beyond", so maybe change to something similar to what  @lwjohnst86 suggested.

What about the weighing of the  four categories, shuold each be worth 8 p? I was initially thinking that we should make the "content" category 10 p, and reduce one of the other categories. However, I think all these are crucial for reproducible science, although something like "style" does not sounds as important at first, it will be an integral part of our course. So I think all categories should be weighted equally, but maybe we can add to the "style" rubric lowest and highest grade definitions to show include reproducibility as a measure:

C. "...poorly document **and very difficult to reproduce analyses**"

A.  "...well-documented, **easily reproducible analyses,** publication-ready

**Comment by mbonsma** [comment]
@lwjohnst86 @linamnt I think we can change `above and beyond` to something a little less intense, because I agree, I think A should be 'exceeds expectations' but that our expectations shouldn't be that crazy.

**Comment by lwjohnst86** [comment]
Done :)
