### ISSUE TITLE
Need to make an explicit page for describing the final assignment?

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/rcourse#155]
Probably, but what should we include in it exactly?

**Comment by joelostblom** [comment]
Isn't it enough to make it as an assignment? Include the rubric and a general description. It would be nice to link to example reports I guess... But it might be hard to find that (maybe Chritsie's class from this year has some) and we don't want them to copy.

**Comment by lwjohnst86** [comment]
Right, that's really what I meant. I guess I'll put that up soon then.

**Comment by lwjohnst86** [comment]
See #157
