### ISSUE TITLE
Suggestions Lecture 16 - Plotting and GitHub collaboration

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/rcourse#166]
Lindsay ~30 min plotting, including:
1. Saving files
2. Oversaturated dot graphs and how to avoid them
    - Mention summaries, briefly repeat the pros and cons from last lecture
    - Go through 2D histograms, [square](http://ggplot2.tidyverse.org/reference/stat_summary_2d.html) and [hexagonal](http://ggplot2.tidyverse.org/reference/geom_hex.html) bins. (I think those are the relevant links, but I don't use ggplot much so not sure.
3. Colorblind friendly plots
    - Never use the jet heatmap (it's terrible for people who are not colorblind also)
    - Use colorscales from low to high luminosity 
    - Change markers per group in addition to changing color
    - [Upload a figure on this site](http://www.color-blindness.com/coblis-color-blindness-simulator/) and see how it looks for a colorblind person.

After that I will talk about collaboration on GitHub and Gitter for ~20-30 min, then break, then project work.

**Comment by joelostblom** [comment]
@lwjohnst86 Just to confirm, you focused on using Git from the command line right, not from within R studio? Do you have a preference for whether I recap the R studio git workflow or the command line one? I would lean towards the command line one because it is more versatile, and it is what you and @QuLogic talked mostly about.

**Comment by lwjohnst86** [comment]
Yes, I think that is fine re the command line. Maybe I'll take a few minutes after you do your talk to just remind them and show them a bit about how to use RStudio Git Interface.

**Comment by joelostblom** [comment]
Do you think we should stick to one of the approaches? I am worried it becomes messy for them if we introduce two ways of doing the same thing, this is already brand new to them. I don't have experience using Git/GitHub through RStudio, but if you think that is easier, I think we should focus on that way of using version control. They will probably use R-studio for all their text editing anyways.
