### ISSUE TITLE
Mention mixed-effect modelling next week

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/rcourse#175]
Martin said that both datasets and their hypotheses look like they'll need to use mixed-effects modelling, so @lwjohnst86 could you maybe mention that to the groups at the next class? I know you brought it up during your lectures, but maybe just to remind them and tell them a bit more about it and that you can help them implement it.

Blog post about doing it in R: https://uoftcoders.github.io/rcourse/lec11-modelling.html

**Comment by lwjohnst86** [comment]
Sure! Mixed effects modelling is fun!

**Comment by joelostblom** [comment]
Specifically, he was talking about how the different species would need to be taken into account when the student modelled the relationship between different variables. He seemed to assume that they will model something, although we are not technically enforcing this at them moment, it would be a good idea to nudge students in that direction (in addition to their current more analytical quesitons). he mentioned the `lmer` package in R, which I think is what you meant to link to above  @mbonsma .

**Comment by lwjohnst86** [comment]
Yes, that is the package to use for mixed effects modelling. I've done a bit of it in my work (actually my stats I use are very similar to mixed effects). Maybe we can have a short session on it one of the project days.

**Comment by lwjohnst86** [comment]
Done :)
