### ISSUE TITLE
Add favicon to home page

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/rcourse#176]
Because duh... We need some style! (also because I run with no tab titles and it is always difficult to find the empty tabs...).

How about this, I just screenshotted some colorful distribution lines. It's so small no one really cares, just need something =)

![favicon-96x96](https://user-images.githubusercontent.com/4560057/32352766-f597e1ee-bff8-11e7-8dc2-eed505747cb5.png)
(transparent bg)

![image](https://user-images.githubusercontent.com/4560057/32352631-676fe83a-bff8-11e7-83c4-13ef83ba246a.png)
(white bg)

**Comment by lwjohnst86** [comment]
Nice. I did it, but the distribution lines are too thin. Not sure if you are able, but is it possible to get ones with a thicker lines? Transparent works well, though the white bg might work if it wasn't so ... boxy

**Comment by joelostblom** [comment]
How about this guy?

![image](https://user-images.githubusercontent.com/4560057/32371692-32d34c00-c068-11e7-9a74-39624e35ffb6.png)
