### ISSUE TITLE
Create issue in each group repo on todo list as guideline?

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/rcourse#184]
So they have a sense of "this is what we need to achieve to complete this assignment"?

**Comment by joelostblom** [comment]
Let's put this up maybe next week? I just want them to think a little bit
about it themselves first and not give them a perfect protocol to follow
right away. I think they will appreciate the guidelines more when they have
also given it some thoughts themselves. We can also add items incrementally
as the projects progresses.

**Comment by lwjohnst86** [comment]
Too late now. And I don't think we really needed to anyway.
