### ISSUE TITLE
Draft syllabus (with detailed descriptions)

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/rcourse#192]
Here's a draft syllabus that @aays and @James-S-Santangelo came up with today. Comments and edits are much appreciated!

| Lecture | Topic | Description | Instructor |
| ---------- | ------- | --------------- | ------------- |
| 1 |  Intro to course, programming, RStudio, R Markdown | Introduction to course format, setting up RStudio | Ahmed
| 2 | Assignment, vectors, functions | Introduction to R notebooks, programming in R | Ahmed
| 3 | Data frames, intro to dplyr | Examining a sample dataset, data frame manipulation with dplyr | Ahmed 
| 4 | Data wrangling in dplyr, ggplot, tidy data | dplyr continued, plotting with ggplot2 | Ahmed
| 5 | More dplyr and ggplot | Reshaping data, reproducing figures using ggplot2 | Ahmed
| 6 | Exploratory data analysis | Plotting, outliers, missing data, etc. - based on paper James put on Gitter | Lindsay
| 7 | Linear models and statistical modelling | Linear regression, multiple regression, logistic regression, ANOVA, ANCOVA, post hocs etc. | Lindsay |
| 8 | Mixed effects models | Fixed vs. random effects, random intercept models, nested designs, repeated measures |  James  |
| 9 | Simulating data | Generating null distributions, Randomization tests (e.g. permutation tests, bootstrapping | James  |
| 10 | Multivariate stats | PCA, factor analysis, path analysis, etc. | Lindsay |
| 11 | Model selection | Criterion-based model selection (e.g. AIC, AICc, BIC), model averaging |  James |
| 12 | Numerically solving population models | Plotting common ecology models in R, numerically solving differential equations | Madeleine
| 13 | Time series analysis | Least-squares fitting of times series data to models, possibly Maximum Likelihood, possibly Gillespie simulation if time | Madeleine
| 14 | Datasets, hypotheses, begin projects | | Everyone 
| 15 | Reproducible science | Reproducible workflow, metadata, markdown, Git and GitHub | Lina or Sara
| 16 | Reproducible science | Git and GitHub, scientific collaboration, scientific publishing  | Lina or Sara

**Comment by lwjohnst86** [comment]
Looks good. Will one lecture on mixed effects models be enough?

I assume there rest of the lectures are project work?

**Comment by James-S-Santangelo** [comment]
I think one lecture would be enough since the previous lecture will be a primer on linear models. I'm thinking it would cover the basics (e.g. random intercept, nested designs) but not advanced stuff like random slope models. Thoughts?

**Comment by lwjohnst86** [comment]
Fair enough. Much better than our zero lectures on mixed models last year :P but we didn't know going in and we had other topics to focus on.

**Comment by James-S-Santangelo** [comment]
@lcoome Do you have a preference for how you would like to split-up the stats lessons?

**Comment by linamnt** [comment]
Sorry not sure why I missed this, but it looks good to me, and I'm happy to do the reproducibility lectures :+1: 

But also, how much Git/Github would go into that last lecture? Just as an overview of what is possible?

**Comment by James-S-Santangelo** [comment]
FYI @mbonsma @aays @lcoome , I have added descriptions for my modules to the syllabus.

**Comment by mbonsma** [comment]
I'm adding these to the syllabus and I think we have space for one more lecture. Any suggestions for where it should go?

**Comment by James-S-Santangelo** [comment]
@mbonsma Is the space for the additional lecture coming because of the Gittr convo suggesting we trim the intro to R material or do we have extra space in addition to that? I think having a 'spare' lecture after the course material but before the project could be a good idea in case we need to cover material that we don't get a chance to throughout the semester.

**Comment by mbonsma** [comment]
@James-S-Santangelo, in addition to that, even if we don't trim the R section. If you compare last year's schedule to the new one, we have more project work days this year.

**Comment by James-S-Santangelo** [comment]
Having one 'spare' lecture slot + one more lecture for project time seems fine with me. It's also possible that Asher/Marty may have some ideas or want some things shifted around so we could bounce it off of them.
