### ISSUE TITLE
Update final project rubric

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/rcourse#196]
In #5 and #14 we discussed criteria for the final project for last year. 

Below is the rubric from last year. We need to update it to include an oral presentation, and possibly marks for the weekly updates (although currently those are listed separately in the assessment schedule).

### Final project grading rubric

|                                                | Inadequate (0 marks)                                                                                                                                                                                          | Adequate (4 marks)                                                                                                                                                | Excellent (8 marks)                                                                                                                                                                    |
|------------|--------------------|--------------------|--------------------|
| Contribution to group work and self-assessment | Student contributed little to project; self-assessed contributions are low in quality and/or quantity; self-assessment is not consistent with actual contribution.                                            | Student contributed adequately to project; made some significant contributions                                                                                    | Student substantially contributed to project to ensure success; self-assessed contributions are crucial to project; self-assessment is consistent with actual contribution.            |
| Weekly progress (measured in GitHub commits)   | Several weeks in which no contributions are made to project                                                                                                                                                   | Adequate progress on project is made in most weeks                                                                                                                | Significant progress is made every week                                                                                                                                                |
| Content                                        | Missing crucial information; methods and results are inconsistent, not logical, or not adequately explained; conclusions are confusing or unsupported by results; unnecessary information included as clutter | Most essential information included; methods and results are adequately described; conclusions supported by results; most included material is relevant to report | All essential information included; methods and results are succinct, clear, logical, and scientifically valid; conclusions are creative and meaningful; project is concise throughout |
| Style and reproducibility                      | Code and writing are poorly organized, poorly formatted, missing units, difficult to read, poorly documented, difficult to reproduce analyses                                                                 | Code and writing are well-organized, well-formatted, consistent use of units and significant figures                                                              | Code and writing are precise and clear throughout, free of errors, well-organized, well-documented, easily reproducible analyses, publication-ready                                    |

**Comment by James-S-Santangelo** [comment]
What about combining the "Contribution to group work and self-assessment" and "Weekly progress" into a single category termed "Contribution and group participation" or something to that effect. Github commits can still be part of this but we aren't placing as much emphasis on Git/Github this year, although I do think it should still be a component. This would free up an additional slot for the group presentation, which I agree should be a component of this project.

**Comment by mbonsma** [comment]
Sounds good. I think we won't be requiring them to use Git at all, except maybe for submission? What do you think?

**Comment by James-S-Santangelo** [comment]
@mbonsma I suppose we don't have to include Git/Github as a grading component, although Lina will be giving a lecture about it. We could elaborate on it further in the extra lecture but only if there isn't more pressing material that needs to be covered first. I just think the more we can introduce them to reproducibility tools (e.g. Git, Rprojects) the better but it shouldn't come at the expense of Stats/programming since I know Asher and Marty want less emphasis on Git and whatnot this year.

**Comment by mbonsma** [comment]
Agreed, personally I'm all for Git, especially GitHub, as a tool for reproducible research.

How about this (basically removed weekly progress and added presentation category):

### Final project grading rubric

|                                                | Inadequate (0 marks)                                                                                                                                                                                          | Adequate (4 marks)                                                                                                                                                | Excellent (8 marks)                                                                                                                                                                    |
|------------|--------------------|--------------------|--------------------|
| Contribution to group work | Student contributed little to project; self-assessed contributions are low in quality and/or quantity; self-assessment is not consistent with actual contribution.                                            | Student contributed adequately to project; made some significant contributions                                                                                    | Student substantially contributed to project to ensure success; self-assessed contributions are crucial to project; self-assessment is consistent with actual contribution. |
| Content                                        | Missing crucial information; methods and results are inconsistent, not logical, or not adequately explained; conclusions are confusing or unsupported by results; unnecessary information included as clutter | Most essential information included; methods and results are adequately described; conclusions supported by results; most included material is relevant to report | All essential information included; methods and results are succinct, clear, logical, and scientifically valid; conclusions are creative and meaningful; project is concise throughout |
| Style and reproducibility                      | Code and writing are poorly organized, poorly formatted, missing units, difficult to read, poorly documented, difficult to reproduce analyses                                                                 | Code and writing are well-organized, well-formatted, consistent use of units and significant figures                                                              | Code and writing are precise and clear throughout, free of errors, well-organized, well-documented, easily reproducible analyses, publication-ready                                    |
| Presentation                      | Presentation is poorly organized; much too long or much too short; presentation is unclear; presentation is missing information; presentation is not scientific and professional; presentation uses too much jargon; not all team members participate; does not adequately address audience questions            | Presentation is adequately organized; timing is appropriate; most information is presented logically; presentation is scientific and professional; most jargon is avoided; all team members participate but equally; audience questions are sometimes addressed well | Presentation is clearly and logically organized; presentation flows and is easy to follow; presentation includes appropriate information without jargon; presentation is well-rehearsed and high-quality; all team members participate equally; audience questions are clearly addressed |

Overall assessment schedule:

| Assignment | Type | Due | Marks |
| ------------------------ | ------------------ | -------------- | ----------- |
| Getting set up            | Individual          | Sep 18     | 4     |
| Basic R and dplyr         | Individual          | Sep 25     | 8     |
| dplyr and tidy data       | Individual          | Oct 02     | 8     |
| Statistical modelling     | Individual          | Oct 09     | 8     |
| Bootstrapping & multivariate stats            | Individual          | Oct 16     | 8     |
| Model selection and time series analysis    | Individual          | Oct 23     | 8     |
| Project setup             | Project, Individual | Oct 30     | 8     |
| Data visualization        | Project, Individual | Nov 13     | 8     |
| Weekly project updates    | Individual          | -          | 8     |
| Final project work        | Project, Group      | Dec 05     | 32    |

@lwjohnst86 @joelostblom @QuLogic @linamnt @lcoome - do you have comments on the parts of the rubric that we're keeping from last year? Was there anything that was hard to grade or anything you wished students had done that wasn't in the rubric?

**Comment by lwjohnst86** [comment]
Not sure why I didn't see this earlier. Um, I don't recall having much difficulty grading. I do recall an issue with knowing how to grade individual contributions, as we hadn't made a very clear grading scheme/guide for that. That's really only thing I remember.
