### ISSUE TITLE
Change 'project setup' assignment if we're not making GitHub mandatory

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/rcourse#198]
We won't be requiring them to use GitHub for their projects this year. Should we remove or modify [this assignment](https://github.com/UofTCoders/rcourse/blob/master/assignment-07.Rmd) that walks them through setting up on GitHub? 

I think it might be helpful to force them to create a similar structure in whichever collaborative system they're using though, so maybe we can keep it but make it non-specific for things other than GitHub?

**Comment by James-S-Santangelo** [comment]
Yeah I think the assignment itself is a great idea. A lot of students will already have experience Dropbox/Google Drive and may opt for using that route to stay organized. I think we could leave most of the assignment intact in case some students feel like using Github but also add that students may wish to use alternative means of collaborating. Thoughts?

**Comment by mbonsma** [comment]
Yeah, I like that: keep it about GitHub but without forcing them to use it except for submission. If we do ask them to submit on GitHub (which I think we should), the assignment can basically create all the placeholders and structure for the final submission.
