### ISSUE TITLE
Project submission format

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/rcourse#199]
The final project deliverables will be:

* A written report
* Code
* Presentation
* Self-assessment of contribution (maybe just a ranked number from 1 to 8?)

Should we require them to submit their report and code on GitHub? I'm leaning towards yes. Thoughts?

**Comment by James-S-Santangelo** [comment]
I think having them submit via Github is the best option. An alternative would be to have them submit a knitted .pdf or .html file that includes everything (e.g. code, results, discussion, etc.)

**Comment by mbonsma** [comment]
:+1:  It'll be good practice for them to submit on GitHub, since that's what a good open researcher should do!
