### ISSUE TITLE
Create a DOI of the course content at end of class for future reference.

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/rcourse#2]
(This is for future reference and doesn't need to be dealt with now.)

This way, we can reference/cite the tagged final version used in this term for later years, change up the course as we see fit for other purposes (later years, for other universities, for a standalone workshop/course, etc), while still having the previous, citable course.

Thoughts? (again, for later reference. It's not important now)

**Comment by lwjohnst86** [comment]
Why close? I opened this recently as a separate issue

**Comment by joelostblom** [comment]
Sorry, I closed the wrong issue.

**Comment by lwjohnst86** [comment]
I'm going to create a tag of the final content (see comment in #13), so that I can generate a DOI of the final content. Anyone have any strong opinions on using figshare vs Zenodo?

**Comment by joelostblom** [comment]
I haven't used either, but it is my understanding that Figshare actually
published what we select fom our repo on their site, while zenodo just adds
a DOI to the entire tagged repo, is that correct? If so, figshare might
feel more like a real publication for the students.

**Comment by lwjohnst86** [comment]
Didn't realize that about Zenodo. Though this issue is about the course content itself, not the student projects. I was thinking a DOI for the tag (aka the entire repo).

**Comment by QuLogic** [comment]
Zenodo creates a DOI for the tagged contents (e.g., https://zenodo.org/record/49636), not the repo itself. What exactly would we need the DOI for that's not in the repo?

**Comment by lwjohnst86** [comment]
So maybe Zenodo would be better. I was thinking the DOI would be used to cite the tagged "release" of the course content, if/when we publish something on this experience. Rather than cite the tag of the GitHub repo. Does that make sense?

**Comment by joelostblom** [comment]
Sorry, I mixed this up with the students' project repos. Yes, for the
course material I think Zenodo is better. For the students' repo I meant
that a DOI for the tagged repo was too much and we likely want to be more
selective with what to publish (aka, only the final report) and then
figshare might be better?

**Comment by lwjohnst86** [comment]
For anyone that wants to include this in their CV: 

Luke W Johnston, Joel Ostblom, Madeleine Bonsma, Elliott Sales de Andrade, Lina Tran, & Lindsay Coome. (2017, December). UofTCoders/rcourse: EEB430H1 Theoretical Ecology and Reproducible Quantitative Methods in R, Fall 2017 (Version v1.0.0). Zenodo. http://doi.org/10.5281/zenodo.1117433

Author order is based on GitHub commits/additions/deletions (or maybe only commits?). Let me know if this is good. 

Also, if anyone has ORCID, let me know it and I can add it to the DOI.

@mbonsma is this your ORCID? 0000-0002-5813-4664
@linamnt is this you? 0000-0003-3504-4524
@lcoome this you? 0000-0001-8126-3571

@joelostblom I didn't find your ORCID.

@QuLogic I found yours (0000-0001-7310-8942)

**Comment by joelostblom** [comment]
Great, thanks @lwjohnst86 ! My orcid profile/ID is https://orcid.org/0000-0003-0051-3239. I agree with your ordering metric.

**Comment by linamnt** [comment]
Yes that's my ORCID. and the order makes sense.

**Comment by mbonsma** [comment]
Yup, that's my ORCID!
