### ISSUE TITLE
Open Access week for RQM course, Oct 23-29

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/rcourse#22]
_From @joelostblom on March 25, 2017 11:49_

Keep an eye on http://www.openaccessweek.org/ and see if they will post anything that we could mention in the course.

_Copied from original issue: UofTCoders/council#129_

**Comment by lwjohnst86** [comment]
FYI at OCAD: http://www.openaccessweek.org/events/open-for-collaboration-open-access-week-at-ocad-university?xg_source=activity
