### ISSUE TITLE
Assignment 8

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/rcourse#264]
The [old assignment 7](https://github.com/UofTCoders/rcourse/blob/8afcc03db016b86aa2ae8c98cdb41541322ed7a1/assignment-07.Rmd) (before I overwrote it with my assignment) is a good scaffold for what we wanted to include in the last assignment (8):

 - pull requests, forking
 - do stuff with our own temp repository? 
 - grade on quality of commit, that they did it, etc. 
 - create code of conduct

**Comment by James-S-Santangelo** [comment]
This assignment looks really good. I say we go ahead and submit a PR so it can be reviewed. There are a few things we'll need to change (e.g. the master repo is no longer on the UofTCoders GitHub account).

**Comment by mbonsma** [comment]
Sounds good! Do you want to open the PR?

**Comment by James-S-Santangelo** [comment]
Sure thing! I'll get to it in the next couple of hours
