### ISSUE TITLE
Do you need to be a graduate student to be a TA?

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/rcourse#28]
_From @joelostblom on March 24, 2017 0:41_

Are there restrictions in general for who we can recruit as a helper for the RQM tutorials?

_Copied from original issue: UofTCoders/council#118_

**Comment by joelostblom** [comment]
Is this still relevant? Will we have helpers from UofT Coders?

**Comment by lwjohnst86** [comment]
Seems as though as long as you are a graduate student upon hiring, you can be a TA. Closing
