### ISSUE TITLE
Survey asking about skill level/etc of students, to complete after the first lesson

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/rcourse#38]
I think we discusses this previously. It would be useful to have a survey of the students skill level, familiarity with concepts, etc for our own knowledge and use.

Depending on how we deal with forming groups, this survey could help with that.

**Comment by joelostblom** [comment]
This survey is being developed on UofTCoders google forms account

**Comment by joelostblom** [comment]
I moved the survey I created previously into your new folder. Direct view link https://docs.google.com/forms/d/1YfL98AYlWZzIk2UTPrffuF4a86X6IgqGrSuQcIaSh8M/edit?usp=sharing

**Comment by joelostblom** [comment]
Survey approved at meeting.
