### ISSUE TITLE
How to form groups?

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/rcourse#39]
So the discussion is formalized here. What does everyone think about how the groups will be formed?

I recall we talked about having groups with varying skill sets involved. I like that approach, but how will be actually go about doing that? Randomly split them based on skills? Or some other criteria?

Thoughts?

**Comment by joelostblom** [comment]
I think we should design a survey, as you mentioned in the #38, to get an overview of students background knowledge. I believe that it will be a good idea to divide students into groups based on their background experiences.

In my opinion, the main technical skills that will be helpful to have in each group is knowledge of R, Github and Gut, and programming in general. Probably in that order. Lackimg experience of those three skills would definitely slow down groups even if they understand the lecture content well.

**Comment by joelostblom** [comment]
Do we need to add this and #38 to the syllabus? Or can we keep it internal?

**Comment by lwjohnst86** [comment]
Makes sense. So we'll create the groups ourselves. I think that works. Yes, we could merge this with #38

**Comment by joelostblom** [comment]
Tracking in #38 instead
