### ISSUE TITLE
Include participation marks?

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/rcourse#40]
Like 5% or something. For random, non-assignment related tasks (e.g. for completing an important exercise in class or something).

**Comment by joelostblom** [comment]
Yes, I agree there should be something like this in the beginning.

**Comment by lwjohnst86** [comment]
We're thinking that the assignment "Reproducible workflow" be removed and use that mark for participation/attendance. Since the assignment is redundant with the GitHub/Git and Rmarkdown lectures and assignment (number 7).

**Comment by lwjohnst86** [comment]
@mbonsma suggests if the student misses more two classes then marks start decreasing (1 or 2 marks each missed class).

**Comment by joelostblom** [comment]
There will be 8 marks for participation. These will be taking from the assignment on reproducibility which will be covered elsewhere. Student can miss two classes without any penalty, and will then lose 1 mark per missed class.
