### ISSUE TITLE
Sort lecture files and assignments into folders

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/rcourse#43]
I would suggest a couple of folders named 'lectures' and 'assignments'. @lwjohnst86 Did you already have something in mind for this?

**Comment by lwjohnst86** [comment]
Fortunately or unfortunately, generating websites in R Markdown does not allow using folders/subfolders, so this is the way it's gotta be. There's probably work arounds, but, really, that is a very low priority issue (at least to me). Even for creating books using the `bookdown` R package (this is how the [R for Data Science book](http://r4ds.had.co.nz/) was created), you can see on the [r4ds GitHub repo](https://github.com/hadley/r4ds) all the book chapters are in a single directory.

**Comment by lwjohnst86** [comment]
This is why I added `lec##` to each lecture file.

**Comment by joelostblom** [comment]
Agree, let's close this for now then. I will reopen if we end up with tonnes of files and a big mess, but for now I'm excited and grateful that the site looks so stunningly stylish that I will refrain from jabbing at R =)
