### ISSUE TITLE
Should assignment only cover what has been taught in class?

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/rcourse#46]
Could a few of the questions be an expansion of the material taught during the lesson? Or do we want every concept to be explained in class and then the students work through it with their own data?

**Comment by lwjohnst86** [comment]
I think the first few should be expansions of the material, but as we get into the course, it should shift to dealing with developing their final assignment. Kinda like milestones that we grade.

Otherwise, if each student uses their own data, then marking will be a bit challenging.

**Comment by joelostblom** [comment]
Conclusions after meeting: Assignments can expand on material outside class and we can expect student to find additional information on their own, e.g. via StackOverflow. We should encourage this independent workflow during the lectures.
