### ISSUE TITLE
What's the workflow for grading assignments?

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/rcourse#47]
We discussed this briefly before. Should students submit assignments on blackboard, via email, or as pull requests on GitHub? GitHub would be nice just because it is easy to comment on specific lines of a pull request, but would need many repositories so that they cannot see each others work... I guess it works with inline comments in email as well, but it would not be as easy to render it nicely...

**Comment by lwjohnst86** [comment]
I think for all assignments that don't relate specifically to the final assignment, they should be handed in on blackboard. Or at least the first several. Just so we don't bombard them with new things all at once.

**Comment by joelostblom** [comment]
Ok, sounds reasonable, I will add that to the syllabus
