### ISSUE TITLE
Where should we upload the answers keys to the assignments?

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/rcourse#48]
So that students can't get hold of the answers, should we make the repository private? Or keep them in an encrypted zip? Or make a separate repo?

**Comment by lwjohnst86** [comment]
Good question. We can't do a private repo in an organization account, I don't think. I think it costs. We could put it all in your account or maybe just have individual files that we email around. A private repo on one of our own accounts may be a good idea.

**Comment by joelostblom** [comment]
I think it will still be important for us to comment on the assignments pull request style in order to discuss them, so I prefer not doing email.

We could make a GitLab group for UofT coders... they allow for private repos in organizations, and everyone who does not have a GitLab account can just use their GitHub login, so setup is painless an maybe a fun way to explore GitLab (I have used it some already and it great so far, just no one to play with over there =( )? I could also set up a private personal repo and invite you guys, what do you think?

**Comment by lwjohnst86** [comment]
I like the idea of using GitLab. I also have been using it more and really do enjoy it!

But again, if they submit their assignment through GitLab, that is an additional thing they need to learn. We'll discuss more in the meeting.

**Comment by joelostblom** [comment]
Yes, the students should not submit their assignments there.

I meant that during the development of the assignments, it would be nice for us to give feedback internally in the pull request format on the complete assignments with answers. Without having to worry about students finding the answers in a public repo later.

**Comment by joelostblom** [comment]
@lwjohnst86 see if we can make rcourse private

**Comment by QuLogic** [comment]
https://education.github.com/discount_requests/new I already have an org listed there, so possibly I shouldn't be trying this out for UTCoders myself. IIRC, the discount lasts for 2 years if you get it.

**Comment by joelostblom** [comment]
Thanks @QuLogic ! I just submitted an application for 2 private repos for us. We should hear back within 5 days.

**Comment by lwjohnst86** [comment]
We've got a repo (private) that contains the assignments + answers https://github.com/joelostblom/rcourse-assignments
