### ISSUE TITLE
Decide on which one or two datasets to use

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/rcourse#61]
As per our discussion with Martin, it would make it simpler for us if we limited the choice of dataset they can use, so that trouble shooting on our end is easier. And in terms of grading, inter-team help/problem solving, etc.

**Comment by joelostblom** [comment]
I think this is similar to what we have planned, to provide ~5-6 data sets that we are comfortable with. But I agree that we could limit the number even further, especially if enrolment currently is around 11 students, we will likely not need more than 3 data sets, given that groups could choose the same data set.

Do you think the data sets we choose all be similar (e.g. all time timeseres) and just slightly different "difficulty" level (size and scope maybe)? Or do we want them to be on different areas?  Generally, my opinion is that vastly different data sets choices in not as important as us being able to deliver a great experience for the data set(s) we choose (so I would rather have 1 than 10, although some students might not love that particular one).

We already have the human microbe data set provided by @mbonsma and the many Toronto Open data sets provided by @QuLogic. We could go through the two databases that Martin sent us and select another 3-4 and then choose a total of 1-3 that we want to work with?

**Comment by joelostblom** [comment]
@mbonsma and @lwjohnst86 After spending way too long time looking, I found [this dataset](https://figshare.com/articles/Time_Series_of_plant_biomass_during_1998-2013/4149648), which is a timeseries of biomass for a few plants growing in Abisko in north of Sweden! I am currently using it for the dplyr assignment 3, would it also be suitable for any of the stuff you want to do?

**Comment by joelostblom** [comment]
There is also this collection of ecology data https://ecologicaldata.org/find-data, and this one http://arc-lter.ecosystems.mbl.edu/data-sets-by-project?term_node_tid_depth=5374&title=&field_abstract_value=

**Comment by lwjohnst86** [comment]
Here are some possible datasets:

- Continuous Plankton Recorder Dataset: https://www.gbif.org/dataset/67c54f85-7910-4cbf-8de4-6f0b136a0e34
- Insecta of Costa Rica: https://www.gbif.org/dataset/3e9817c1-8302-4955-87e3-a408db0ea379

Both are pretty big datasets (+150Mb).

**Comment by lwjohnst86** [comment]
I've added some datasets, see #58
