### ISSUE TITLE
For modeling, use data to guide what we teach?

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/rcourse#62]
This is really for @mbonsma and me. Should we first decide on what one or two datasets we give them before completely fleshing out the lecture material? Makes it easier for us and easier for the students. So we can focus on teaching material that we think they will actually use in the project.

**Comment by mbonsma** [comment]
Yeah, I agree. We should pick a sample dataset that we use for everything. Do you know if R has any built-in ones that would suffice, or should we just give one to them at the beginning?

**Comment by lwjohnst86** [comment]
Yes, there are several. I have been planning on looking for some possible datasets that we can decide to use ... after my thesis defence :D

**Comment by joelostblom** [comment]
@lwjohnst86 You have such strange priorities! No really, thanks so much for still replying to issues and PRs here although your defense is just around the corner. Don't hesitate to say that you don't have time!

For data, I found a cool one that I used for assignment-03 and [uploaded here](https://github.com/UofTCoders/council/blob/master/datasets/joel/plant-biomass-preprocess.csv). It is from [this figshare link](https://figshare.com/articles/Time_Series_of_plant_biomass_during_1998-2013/4149648). The [issue it was published in](http://rstb.royalsocietypublishing.org/content/368/1624) is called "Long-term changes in Arctic tundra ecosystems", so it might have more data of use in case we need it. I also found [this database](https://www.gbif.org/), potentially useful.

**Comment by lwjohnst86** [comment]
Haha, yea, thesis is pretty important but I'm pretty confident in it. Plus I like to chunk my time and I've chunked this half of the day to working on RQM stuff.

Thanks for those links! That database is quite useful!
