### ISSUE TITLE
Survey students about how challenging the course is?

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/rcourse#63]
Martin's mentioned that it is key to adjust the level of teaching to the student's ability, so that students don't feel either bored because it is too easy or lost because it is too hard. How do we want to keep an eye on student's opinion of the teaching level?

We will have the results from the assessments, and students can always contact us via email. Do we want to add a survey (maybe after each block) to actively encourage students to give their opinion about how challenging the course is?

**Comment by lwjohnst86** [comment]
Yes, 100% for suuurreeee. However, I think we should only do this twice, once in the middle and once at the end.

However, we can use the practice exercises during lessons to judge the students' progress. And adjust the material as we go based on that, as well as the mid-survey.

**Comment by joelostblom** [comment]
Great, I am tempted to have three:
- One right after the R lessons in the beginning to see if we lost the entire class already
- One after the theoretical ecology lessons
- One in the end, mostly for us to have an evaluation of the course.

The two first ones are early so that we can act and adjust if necessary.

**Comment by joelostblom** [comment]
The above would be in addition to the practice exercises you mentioned. 

Btw, with practice exercises, are you referring to when we give students a couple of minutes to solve an extension of  a concept that we just thought them? E.g. Take two min to calculate the mean value of column Y for each group, only including observations where column X > 50?

**Comment by lwjohnst86** [comment]
I created a folder in the coders drive for the course. Please use that when creating the survey

**Comment by joelostblom** [comment]
I think the survey I created previously ("Background experience"), covers "Initial survey", "Basic R survey", and "Ecology concepts survey". Let me know what you think.

**Comment by joelostblom** [comment]
View only link https://docs.google.com/forms/d/1YfL98AYlWZzIk2UTPrffuF4a86X6IgqGrSuQcIaSh8M/edit?usp=sharing

**Comment by lwjohnst86** [comment]
For the lecture feedback, do we want specific surveys for each section or do we want one survey that we re-use and is general enough?

**Comment by joelostblom** [comment]
I was thinking a general one for reuse, like "was it too fast/slow?", "do you  feel it's relevant" type of thing. But since we will probably make copies of the survey to separate answers, I think it's ok if anyone has idea for section specific questions.

**Comment by lwjohnst86** [comment]
I agree. I've put in the survey a question asking which lecture just finished. I assume we will only give these out twice right? Or how many times did you say?

**Comment by joelostblom** [comment]
I am thinking 2-3 times
1. After my lectures (Sep21, to make sure everyone is onboard with programming)
2. After @mbonsma and you have had the modelling related lessons (Oct12, to make sure everyone is following the new ecology concepts)
3. (Maybe) Just before fall break (Nov2, to see that they have gotten started with the project and are not totally confused about what to do next)

Then there will be one evaluation survey after the class, but that one will looks slightly different I guess.

**Comment by joelostblom** [comment]
Conclusion from meeting: @lwjohnst86 will update the current version of the survey [Lecture Feedback](https://docs.google.com/forms/d/1z5vlLcCvcY4Qee0rHGzpsdmgAkFvsJc33NeoKeBgF7Y/edit?usp=sharing) (only accessible if you're logged in to your invited gmail address) with his 

The survey will take place 3 times, Sep21, Oct12, and Nov2 (as outlined in my previous post). Filling out this survey is anonymous and optional, but we should encourage to do this the last 5 min of the respective class.

We should make three separate surveys to be able to separate the replies easily. And so that we can have some additional questions for the No2 survey regarding how they feel about starting their project.
