### ISSUE TITLE
Encourage students to use GitHub and Gitter as their primary ways of communication?

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/rcourse#64]
One of our grading criteria is on continuous progress. We will already now have access to their commit history and some level of discussions in issues depending on how the students use it. Student's will likely also use some sort of chat service to coordinate meetings etc.

It would be nice if students used GitHub and Gitter almost exclusively instead of email and standard chat apps. Both because this will make them become familiar with this workflow faster and it will facilitate fair grading, since we can take part of their entire discussion and see who leads the group in terms of setting up meetings, making sure deadlines are met, etc.

#### Potential drawbacks:
- Students feel anxious that what they discuss withing the group can be viewed by their TAs (and everyone on the internet if the repo is public).
    - This is how they are likely to work in the future and it is important getting exposed to it and experience having their professional opinion associated with the name online.
    - They can always send emails between each other for matters they regard as confidential.
- More work for us in grading the chat history.
    - We don't have to go through it in minute detail. It is more to see if someone really pulls all the weight in a team or if some teams don't communicate at all.

**Comment by lwjohnst86** [comment]
Hmm, I would love for this to happen, however, I don't think we should force it. They will already be learning a lot as it is, so I don't know whether this will be too much, for a small gain on our end (and a possible small gain on theirs too, but they will be busy!). Definitely for the final assignment they should use GitHub, but otherwise... I dunno mate.

**Comment by joelostblom** [comment]
Yeah, I was referring to all the communication within the groups for the final projects. Sorry for being unclear. I understand the argument for them being busy with many other things and we don't want to overload them. But I think that for example Gitter would be a small addition that would be easy to set up, and make it much easier for them to chat about specific pullrequests or issues since they can refernce them directly. I think we can even show them how to set up the Gitter and confirm that theirs are working during a project work lecture.

**Comment by lwjohnst86** [comment]
I can add a Gitter badge to the created group repo's

**Comment by joelostblom** [comment]
After meeting conclusion: Encourage students to use GitHub as much as possible so that there is progress we can track. We will not check Gitter, Slack, Riot or similar, but we should encourage them to use these service for their own benefit.
