### ISSUE TITLE
Include working with timeseries data in dplyr?

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/rcourse#65]
I don't really have experience with timeseries, and I was initially thinking of not including it. However, it seems to be a prevalent data type to work with in ecology, and Martin mentioned that one of the databases largely is species abundance over time, so I think we should include this. I add it to one of the assignments, probably the last one.

**Comment by lwjohnst86** [comment]
Yea, it might be a good idea. @mbonsma are you planning on covering much timeseries stuff in your lessons?

The nice thing is that R has a lot of built-in timeseries capability that is, actually, quite easy to use and powerful.

**Comment by mbonsma** [comment]
@lwjohnst86 I think it would make sense to include around the time of my lectures, yeah. Can you point me to some timeseries in R information?

**Comment by joelostblom** [comment]
There a [chapter on dates and times]( http://r4ds.had.co.nz/dates-and-times.html) in the R for data science book.

**Comment by lwjohnst86** [comment]
@joelostblom I think what @mbonsma means is timeseries analysis, not date and time formating. 

Here's some resources for timeseries:

- [forecast](https://cran.r-project.org/web/packages/forecast/index.html) package and it's intro [vignette](https://cran.r-project.org/web/packages/forecast/vignettes/JSS2008.pdf)
- [Walk through](http://r-statistics.co/Time-Series-Analysis-With-R.html) of some base R timeseries analyses

**Comment by lwjohnst86** [comment]
@mbonsma here's a [cheatsheet](https://www.datacamp.com/community/blog/r-xts-cheat-sheet?fb_ref=fGnFxpk9p3-Twitter&utm_content=buffer0b542&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer) on timeseries!

**Comment by joelostblom** [comment]
@mbonsma I found [this course on time series in R](https://timeseriescourseemb.wordpress.com/) from Stockholm University. All slides and code available online, they mostly use a special package - MARSS.

General question - is the need specifically for modelling and forecasting of timeseries? If we stick to yearly sampled data, isn't time series _analyses_ often just as simple `group_by(year)` with `dplyr`?

**Comment by lwjohnst86** [comment]
Excellent, thanks! And as for the general question, no, time series is more complex than that. It requires decomposing the data into seasonal and trend data, among other things. dplyr is not able to conduct time series analysis on its own.
