### ISSUE TITLE
Plan for the first class

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/rcourse#71]
This is for the first lecture, exactly one week from now!

This is what I imagine for the first class.
1. Martin talks for ~15 min and then the stage is ours.
2. I spend 10 min introducing the general concept of the class, why are excited to teach it, and how we will work throughout the semester. I also talk about the logistics of the class a bit, that we will use github and blackboard, how assignment will be distributed etc.
3. I am in favor for walking through the syllabus by each person taking ~4 min introducing themselves, what they will teach, and why they are excited over reproducible/quantitative/programming skills and an open science workflow, and how learning these skills have helped them in their research.
4. (We should be around 40 min into the class now, have a break? or continue since it is a lightweight first class anyways? If we have a break, we can say a few words to Martin and then those who want to  leave can do so)
5. I talk about intro to programming ~(30min)
6. I talk about intro to Rstudio and Rmarkdown (~30min)
7. Should I bring up the first assignment anything? 

I imagine we don't have to bring up every single item on the syllabus, like academic integrity etc, just mentioning that they need to read the syllabus should be sufficient?

**Comment by joelostblom** [comment]
The flow of 5. and 6. above will be
- Graphical vs text based input to a computer (aka LibreOfficeCalc vs R command line)
- More advanced programming interfaces such as RStudio
- Scripts enables automation and increases reproducibility
- R Markdown / notebooks are the next generation scripts for exploratory data analyses
    - Includes an example of a notebook I made earlier, just as a preview of what kind of end product / report is possible to make with relatively simple measures.

I am not sure whether this first lesson should be conde along, or more of a high level demonstration of how things work. I am leaning towards the latter since I just want to provide a conceptual understanding at this point. All the other lessons will be code along, and we will start from the beginning with R-studio in the next class, so I would rather have them pay full attention than focusing on getting something to work on their computer, thoughts?

**Comment by lwjohnst86** [comment]
+1 for number 4. Break is a good idea. We'll have to be firm with the length of the break otherwise it can easily extend to more time...

**Comment by lwjohnst86** [comment]
I agree, first lecture should be more high level, since we won't have much time to get started since we'll be going over intros, etc.

**Comment by mbonsma** [comment]
It is a two hour lecture, so I think in the second hour you might as well start with code along, no?

**Comment by mbonsma** [comment]
I take it back! Discussed in meeting.

**Comment by joelostblom** [comment]
I will upload the material for the second half later tonight.
