### ISSUE TITLE
Create end of year survey

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/rcourse#72]
For feedback on what was good etc

**Comment by lwjohnst86** [comment]
We've done this right? Pretty much just the other survey's, slightly modified.

**Comment by joelostblom** [comment]
We haven't really done this, I would like to add some question. Maybe have them highlight what they really liked about the course or something like that. Let's keep it open until that survey is done completely.

**Comment by joelostblom** [comment]
Ideas for additional questions to include:

- Did you need to spend more time/effort on this class than other classes?
- Was this group project more or less structured than your previous group projects? Which pros and cons did you encounter due to this?
- Which skills did you develop in this class that you have not had a chance to develop in other classes?
    - Did you have to be more or less creative/autonomous vs other classes? (Could this be interpreted as leading? It would be good data to have to see if their experience line up with our expectations)

Something along those lines.

**Comment by lwjohnst86** [comment]
done. students completed it.
