### ISSUE TITLE
Send out interesting articles to students as voluntary reading?

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/rcourse#86]
I added a few articles in  #13 that could be good for us, when we want to publish something after the course is over. I realized that some of the students might be interested in these as well. We could send them out maybe a few weeks into the course. One article per week or something as inspiration? We could also collect links to them at the webpage somewhere.

**Comment by joelostblom** [comment]
Also blog posts like this http://predictiveecology.org/2016/10/21/Rmarkdown-science-workflow.html

**Comment by joelostblom** [comment]
http://r4ds.had.co.nz/r-markdown-workflow.html

**Comment by joelostblom** [comment]
You get the idea

**Comment by lwjohnst86** [comment]
I would put these in the `resources.Rmd` file and refer the students to this page for more info.

**Comment by joelostblom** [comment]
Let's keep this open also until I actually put them there in resources.
