### ISSUE TITLE
Announce relevant UofT coders sessions to the EEB430 students?

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/rcourse#88]
Mainly:
- September 14 - Introduction to Programming in R
- October 5 - Introduction to Version Control with Git & Github
- October 12 - Coworking Session - Using Git

There will be overlap with our lectures, but could be a good way for them to learn the material better and meet other people who are using these tools. I realize the timing is a bit unfortunate since they will have had class for 2 hours on Thursdays already. I would also double check with Martin and Asher that we are allowed to advertise these sessions.

**Comment by lwjohnst86** [comment]
Yes, totally. I doubt this is an issue at all since, like we are using UofTCoders repos, rcourse material, UofTCoders  GitHub Pages website, we mentioned we are the exec, etc. Definitely mention it!

**Comment by lwjohnst86** [comment]
If you want to check with Martin/Asher, go ahead, but I don't think they will care. Plus, they probably are super busy people, so ... as the saying goes "better to ask for forgiveness than to seek permission"
