### ISSUE TITLE
Why does RStudio start with second level headers (##) instead of first level (#) in the Notebook?

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/rcourse#90]
@lwjohnst86 Did you say this was related to how slides are made from R Markdown?

**Comment by joelostblom** [comment]
To clarify, I am referring to the template after clicking `File -> New -> R Notebook`

**Comment by lwjohnst86** [comment]
I don't see this when I create a notebook. What's your RStudio version? You can also show me tomorrow.

**Comment by joelostblom** [comment]
Sorry, it is in `File -> New -> R Markdown`, I mixed them up (RStudio 1.0.143). You also have it in [the lecture template](https://raw.githubusercontent.com/UofTCoders/rcourse/master/_templates/lectures.Rmd), so I thought there was some reason not to use first level headings with R Markdown/Notebook.

**Comment by lwjohnst86** [comment]
I'm not sure about the R Markdown template from RStudio, but for the lesson template, I did it for really only one reason: It looks better on the website with smaller headers. First level headers conflicts in size with the title of the website, and they are just overbearing with how big they are. I think Title and First Level Headers use the same css style, so using `##` differentiates them.

**Comment by joelostblom** [comment]
Makes sense, I do that myself sometimes also for the same reason.
